/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
 * Generated on: 27-Aug-2020 16:41:25
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 61
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2017b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
#define LPL 61
Int16 LP[61] = {
     1544,    255,    274,    295,    315,    335,    356,    376,    396,
      416,    436,    456,    475,    494,    512,    530,    547,    563,
      578,    591,    605,    616,    628,    638,    645,    654,    660,
      665,    668,    670,    670,    670,    668,    665,    660,    654,
      645,    638,    628,    616,    605,    591,    578,    563,    547,
      530,    512,    494,    475,    456,    436,    416,    396,    376,
      356,    335,    315,    295,    274,    255,   1544
};
